Repository scalar-labs/scalar-admin-for-kubernetes, pull requests merged in 2023-12, with the labels that each got.

#21 Rename scalar-admin-k8s to scalar-admin-for-kubernetes
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  cli/Dockerfile
  cli/build.gradle
  cli/src/main/java/com/scalar/admin/k8s/Cli.java
  cli/src/main/java/com/scalar/admin/k8s/Result.java
  cli/src/main/java/com/scalar/admin/k8s/ZoneIdConverter.java
  lib/archive.gradle
  lib/src/main/java/com/scalar/admin/k8s/PausedDuration.java
  lib/src/main/java/com/scalar/admin/k8s/Pauser.java
  lib/src/main/java/com/scalar/admin/k8s/PauserException.java
  lib/src/main/java/com/scalar/admin/k8s/Product.java
  lib/src/main/java/com/scalar/admin/k8s/TargetSelector.java
  lib/src/main/java/com/scalar/admin/k8s/TargetSnapshot.java
  lib/src/main/java/com/scalar/admin/k8s/TargetStatus.java
  lib/src/test/java/com/scalar/admin/k8s/ProductTest.java
  lib/src/test/java/com/scalar/admin/k8s/TargetSelectorTest.java
  lib/src/test/java/com/scalar/admin/k8s/TargetSnapshotTest.java
  lib/src/test/java/com/scalar/admin/k8s/TargetStatusTest.java
  settings.gradle
Labels: improvement

#22 Typo
  lib/archive.gradle
Labels: bugfix

#26 Add a workflow to remove untagged images regularly
  .github/workflows/remove-untagged-images.yaml
Labels: improvement

#24 Use Temurin's base image
  cli/Dockerfile
Labels: improvement

#25 Fix the secring file path
  .github/workflows/release.yml
Labels: bugfix

#20 Add README with CLI usage descriptions
  README.md
Labels: documentation
