Repository scalar-labs/scalar-admin-for-kubernetes, pull requests merged in 2024-01, with the labels that each got.

#27 Rename the folder fro `k8s` to `kubernetes`
  cli/src/main/java/com/scalar/admin/kubernetes/Cli.java
  cli/src/main/java/com/scalar/admin/kubernetes/Result.java
  cli/src/main/java/com/scalar/admin/kubernetes/ZoneIdConverter.java
  lib/src/main/java/com/scalar/admin/kubernetes/PausedDuration.java
  lib/src/main/java/com/scalar/admin/kubernetes/Pauser.java
  lib/src/main/java/com/scalar/admin/kubernetes/PauserException.java
  lib/src/main/java/com/scalar/admin/kubernetes/Product.java
  lib/src/main/java/com/scalar/admin/kubernetes/TargetSelector.java
  lib/src/main/java/com/scalar/admin/kubernetes/TargetSnapshot.java
  lib/src/main/java/com/scalar/admin/kubernetes/TargetStatus.java
  lib/src/test/java/com/scalar/admin/kubernetes/ProductTest.java
  lib/src/test/java/com/scalar/admin/kubernetes/TargetSelectorTest.java
  lib/src/test/java/com/scalar/admin/kubernetes/TargetSnapshotTest.java
  lib/src/test/java/com/scalar/admin/kubernetes/TargetStatusTest.java
Labels: bugfix

#28 Upgrade Gradle to 8.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: improvement

#23 Add "required" explanation in "--help" of CLI
  README.md
  cli/src/main/java/com/scalar/admin/kubernetes/Cli.java
Labels: bugfix, documentation

#29 Remove problematic workflow "Remove untagged images"
  .github/workflows/remove-untagged-images.yaml
Labels: bugfix
